name: Format Code

on:
    push:
        branches:
            - main

env:
    NODE_VERSION: 22

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - run: npm ci
            - run: npm run format
            - uses: EndBug/add-and-commit@v9
              with:
                  message: 'Format Code'
                  default_author: 'github_actions'
