name: Node.js Build

on: push

env:
    NODE_VERSION: 22

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - run: npm ci
            - run: npm run build
